pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git branch: 'main', credentialsId: 'Github', url: 'https://github.com/Maggiyerra/Jenkins-Zero-To-Hero'
           }
        }

       stage('Build and Push Docker Image') {
           environment {
               DOCKER_IMAGE = "maggi19/python-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "/python-jenkins-argocd-k8s/spring-boot-app/Dockerfile"
               REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
          steps {
            script {
                sh 'cd python-jenkins-argocd-k8s && docker build -t ${DOCKER_IMAGE} .'
                def dockerImage = docker.image("${DOCKER_IMAGE}")
                docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                    dockerImage.push()
            }
        }
      }
    }
        
        /*stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/Maggiyerra/Jenkins-Zero-To-Hero/python-jenkins-argocd-k8s/deploy',
                branch: 'main'
            }
        }*/
         stage('Update Deployment File') {
             environment {
                 GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
                 GIT_USER_NAME = "Maggiyerra"
        }
            steps {
                withCredentials([usernamePassword(credentialsId: 'Github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    sh '''
                    /*git config user.email "abhishek.xyz@gmail.com"
                    git config user.name "Abhishek Veeramalla"*/
                        BUILD_NUMBER=${BUILD_NUMBER}
                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" deploy.yaml
                        git add deploy.yaml
                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                        git push https://github.com/Maggiyerra/Jenkins-Zero-To-Hero.git HEAD:main
                    '''
            }
        }
    }
       
  }
}
